
const int LARGEUR_BRIQUE_PAR_DEFAUT= 40;
const int HAUTEUR_BRIQUE_PAR_DEFAUT= 20;
const int RESOLUTION_X_PAR_DEFAUT= 800;
const int RESOLUTION_Y_PAR_DEFAUT= 600;
const int LARGEUR_RAQUETTE_PAR_DEFAUT= 100;
const int HAUTEUR_RAQUETTE_PAR_DEFAUT=10;
